# Generated by Django 5.0.6 on 2024-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompostName', models.CharField(max_length=255)),
                ('CompostImage', models.FileField(blank=True, null=True, upload_to='composts/')),
                ('CompostType', models.CharField(choices=[('AnimalManure', 'Animal manure'), ('PlantFertilizers', 'Plant-based fertilizers'), ('BiodegradableFertilizers', 'Biodegradable fertilizers')], max_length=30)),
            ],
        ),
    ]
