# Generated by Django 5.0.6 on 2024-05-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blockchain', '0001_initial'),
        ('CompostersAccount', '0001_initial'),
        ('GreenersAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenersAccount.greener'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='CompostersAccount.composter'),
        ),
        migrations.AddField(
            model_name='block',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blockchain.transaction'),
        ),
    ]
