# Generated by Django 5.0.6 on 2024-05-28 18:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompostersAccount', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Location', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326)),
                ('is_staff', models.BooleanField(default=False)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ComposterStatus', models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted')], default='waiting', max_length=50)),
                ('composter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composters', to='CompostersAccount.composter')),
                ('groups', models.ManyToManyField(related_name='greener_groups', to='auth.permission')),
                ('user_permissions', models.ManyToManyField(related_name='greener_user_permissions', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreenerNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('greener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greener', to='GreenersAccount.greener')),
            ],
            options={
                'ordering': ['-Timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manure', models.FloatField()),
                ('brown_material', models.FloatField()),
                ('green_material', models.FloatField()),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('Status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenersAccount.greener')),
            ],
        ),
    ]
