# Generated by Django 5.0.6 on 2024-05-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
