# Generated by Django 5.0.6 on 2024-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0002_greener_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
